Implement "USBCOMP" for USB composition
There are three ERD items about USB composition. They are respectively
1. The module shall support interface bitmask to enable/disable interfaces.
2. The module shall provide non-volatile memory to store USB composition info.
3. The module shall support AT command to set/query/test USB composition.

Currently, the USB ports and functions are configured by "composition-sierra_dev"
script. The USB ports and functions are not changed. So modify the script to
get the ports and functions by "ud_getusbinfo" app. The "ud_getusbinfo" app
will get the information about the ports and functions from the sharing memory
which contains it during boot.

Resolves: QTI9X40-507
Change-Id: I89b557b06686984890ada8fbb9114a10fb2d520b
Signed-off-by: liliu <liliu@sierrawireless.com>

diff --git a/meta-swi-mdm9x40/recipes-bsp/system-core/files/composition-sierra_dev b/meta-swi-mdm9x40/recipes-bsp/system-core/files/composition-sierra_dev
--- a/meta-swi-mdm9x40/recipes-bsp/system-core/files/composition-sierra_dev
+++ b/meta-swi-mdm9x40/recipes-bsp/system-core/files/composition-sierra_dev
@@ -38,17 +38,52 @@ fi
 
 pkill adbd
 
+vid=$(/usr/bin/ud_getusbinfo VID)
+if [ $? -ne 0 ];
+then
+  echo "ud_getusbinfo gets VID failed"
+  vid=1199
+fi
+
+pid=$(/usr/bin/ud_getusbinfo PID)
+if [ $? -ne 0 ];
+then
+  echo "ud_getusbinfo gets PID failed"
+  pid=68C0
+fi
+
+diagstr=$(/usr/bin/ud_getusbinfo DIAGSTR)
+if [ $? -ne 0 ];
+then
+  echo "ud_getusbinfo gets DIAGSTR failed"
+  diagstr='diag'
+fi
+
+serialstr=$(/usr/bin/ud_getusbinfo SERIALSTR)
+if [ $? -ne 0 ];
+then
+  echo "ud_getusbinfo gets SERIALSTR failed"
+  serialstr='smd,tty'
+fi
+
+compstr=$(/usr/bin/ud_getusbinfo COMPSTR)
+if [ $? -ne 0 ];
+then
+  echo "ud_getusbinfo gets COMPSTR failed"
+  compstr='diag,ffs,serial'
+fi
+
 #echo $mode > /sys/bus/platform/devices/usb_bam/enable
 echo 0 > /sys/class/android_usb/android$num/enable
-/usr/bin/ud_getusbinfo VID > /sys/class/android_usb/android$num/idVendor
-/usr/bin/ud_getusbinfo PID > /sys/class/android_usb/android$num/idProduct
+echo $vid > /sys/class/android_usb/android$num/idVendor
+echo $pid > /sys/class/android_usb/android$num/idProduct
 echo 239 > /sys/class/android_usb/android$num/bDeviceClass
 echo 2 > /sys/class/android_usb/android$num/bDeviceSubClass
 echo 1 > /sys/class/android_usb/android$num/bDeviceProtocol
-echo diag > /sys/class/android_usb/android$num/f_diag/clients
-echo smd,tty > /sys/class/android_usb/android$num/f_serial/transports
+echo $diagstr > /sys/class/android_usb/android$num/f_diag/clients
+echo $serialstr > /sys/class/android_usb/android$num/f_serial/transports
 echo QTI,BAM2BAM_IPA > /sys/class/android_usb/android$num/f_rmnet/transports
-echo diag,ffs,serial,rmnet,ecm > /sys/class/android_usb/android$num/functions
+echo $compstr > /sys/class/android_usb/android$num/functions
 echo 1 > /sys/class/android_usb/android$num/remote_wakeup
 
 echo "Sierra Wireless, Incorporated" > /sys/class/android_usb/android$num/iManufacturer
