timezone: Add timezone utilities
Utilities for timezone handling. Added timezone startup
handling as well.

Timezone handling
=================

In the regular system, file /etc/timezone is plain text
file containing timezone string (e.g. America/Vancouver).
File /etc/localtime is actually soft link which points
to timezone file
(e.g. /usr/share/zoneinfo/America/Vancouver).

If timezone needs changing, /etc/localtime target would
change, as well as content of /etc/timezone.

Our system is using read-only rootfs, and in some cases
its parts would be overlayed by read-write file system.
One of the overlayed file system parts is /etc.

In order to satisfy read-only and read-write system
requirements:

* /etc/localtime is pointing to /usr/share/zoneinfo/localtime
* /usr/share/zoneinfo/localtime contains default timezone
  information (Universal).
* /etc/timezone is guarantied to be writable once the system
  boots up.
* If the timezone needs changing, /etc/timezone will be updated
  with new timezone information, and correct timezone file
  will be bind mounted onto /usr/share/zoneinfo/localtime .
  This way, /etc/localtime would point to correct timezone
  file.
* If possible, /etc/localtime would point to one of
  Etc/GMTxx files. Otherwise, it will point to one of city
  files (e.g. /usr/share/zoneinfo/America/New_York).
* If the system contains read-write overlay, timezone
  settings will be preserved over reboots and power
  downs.

tzoneset
========

This executable should be called as follows:

./tzoneset <time_sec> <utc_offset_sec> <dst>

where:

(unsigned long) time_sec - seconds from epoch. Can be positive only.
Setting this value to 0 means that time should not be set, otherwise
time will be set along with timezone.

(signed long) utc_offset_sec - UTC offset in seconds. Can be positive,
negative or 0.

(signed int) dst - DST in hours. Can be positive or 0.

Caller should check the return code from tzoneset. In case of an error,
tzoneset will return non-zero integer, 0 otherwise.

tzoneset must execute timezone change operation in an atomic fashion. In
order to achieve that goal, /var/lock/.tzoneset.lock file will be
created upon launch, and removed prior to tzoneset exit.

If this file already exist, tzoneset will refuse to run, and will exit
immediately returning non-zero integer.

Resolves: LXSWIREF-757
Related: LE-10348
Change-Id: Icfefb770e4bd3b869b90bd2c81ce7ac2dba7b483
Signed-off-by: Dragan Marinkovic <dmarinkovi@sierrawireless.com>

diff --git a/common/recipes-core/initscripts/files/mount_unionfs.in b/common/recipes-core/initscripts/files/mount_unionfs.in
--- a/common/recipes-core/initscripts/files/mount_unionfs.in
+++ b/common/recipes-core/initscripts/files/mount_unionfs.in
@@ -16,6 +16,96 @@ root_firmware_g=/lib/firmware
 @endif
 overlayfs_sig_g=${OVERLAYFS_SIGNATURE}
 ufs_type=${UFS_T}
+etc_is_writable_g=${SWI_FALSE}
+
+# I've found cases where /etc/localtime is pointing to /etc/TZ,
+# and we need to fix it, if possible.
+# This will only work if /etc is writeable.
+localtime_fixup()
+{
+    local ret=$SWI_OK
+    local localtime=""
+    local timezone_files_root=/usr/share/zoneinfo
+    local sl_localtime=/etc/localtime
+    local real_localtime=$timezone_files_root/localtime
+    local timezone=""
+    local timezone_file=/etc/timezone
+    local default_tz="Universal"
+
+    if [ "x${etc_is_writable_g}" != "x${SWI_TRUE}" ] ; then
+        return $SWI_OK
+    fi
+
+    # If timezone mount point does not exist, make one.
+    if [ ! -f $real_localtime ] ; then
+        swi_log "Creating [$real_localtime] mount point."
+        touch $real_localtime
+    fi
+
+    # Make sure that timezone string exists. If it does not,
+    # setup default.
+    if [ ! -f $timezone_file ] ; then
+        timezone="$default_tz"
+        swi_log "Using default timezone [$timezone]."
+        echo "$timezone" >$timezone_file
+    else
+        timezone=$( cat $timezone_file )
+        swi_log "Using timezone [$timezone]."
+    fi
+
+    # Make sure that timezone exists.
+    if [ ! -f $timezone_files_root/$timezone ] ; then
+        swi_log "[$timezone] does not exist, using [$default_tz]."
+        timezone="$default_tz"
+        echo "$timezone" >$timezone_file
+    fi
+
+    # /etc/localtime must point to proper timezone file.
+    localtime=$( readlink -f $sl_localtime )
+    if [ "x$localtime" != "x$real_localtime" ] ; then
+        # None of this should fail, it's RW file system.
+        rm -f $sl_localtime
+        ln -s $real_localtime $sl_localtime
+    fi
+
+    # We always have to do this, because overlay is mounted on /etc
+    # after timezone initial mount bind (take a look at
+    # mount_early:mount_early_set_timezone() )
+    umount $real_localtime &>/dev/null
+    mount --bind $timezone_files_root/$timezone $real_localtime
+
+    return $SWI_OK
+}
+
+# Make sure that /etc/timezone is writable even if /etc is not.
+set_timezone_writable()
+{
+    local ret=${SWI_OK}
+
+    # If /etc is not writable, make sure that /etc/timezone is.
+    if [ "x${etc_is_writable_g}" = "x${SWI_TRUE}" ] ; then
+        return ${SWI_OK}
+    fi
+
+    # This is only going to work if /etc/timezone exists
+    if [ ! -f /etc/timezone ] ; then
+        # Timezone file is not available, and there is nothing
+        # we should do here. Note that this is not an error.
+        return ${SWI_OK}
+    fi
+
+    # Save timezone content.
+    cat /etc/timezone > /tmp/timezone
+
+    # Now, make sure it appears to be writable.
+    mount --bind /tmp/timezone /etc/timezone
+    if [ $? -ne 0 ] ; then
+        swi_log "Cannot mount /tmp/timezone"
+        ret=${SWI_ERR}
+    fi
+
+    return ${ret}
+}
 
 mount_unionfs_dir()
 {
@@ -83,6 +173,7 @@ mount_unionfs_start()
         if [ $? -ne ${SWI_OK} ] ; then
             return ${SWI_ERR}
         fi
+        etc_is_writable_g=${SWI_TRUE}
     fi
 
     # Try to make /data writable
@@ -103,6 +194,14 @@ mount_unionfs_start()
 @endif
 
     return ${ret}
+}
+
+unset_timezone_writable()
+{
+    # Do not care about the result
+    umount -l /etc/timezone &>/dev/null
+
+    return ${SWI_OK}
 }
 
 # Stop union fs.
@@ -133,9 +232,12 @@ mount_unionfs_stop()
 case "$1" in
     start)
         mount_unionfs_start
+        set_timezone_writable
+        localtime_fixup
     ;;
 
     stop)
+        unset_timezone_writable
         mount_unionfs_stop
     ;;
 
diff --git a/meta-swi-mdm9xxx/recipes-core/initscripts/files/mount_early.in b/meta-swi-mdm9xxx/recipes-core/initscripts/files/mount_early.in
--- a/meta-swi-mdm9xxx/recipes-core/initscripts/files/mount_early.in
+++ b/meta-swi-mdm9xxx/recipes-core/initscripts/files/mount_early.in
@@ -1382,6 +1382,60 @@ mount_early_create_dirs()
     return ${ret}
 }
 
+# Set timezone. This method is in mount_early, because
+# we are mounting various files.
+mount_early_set_timezone()
+{
+    local ret=${SWI_OK}
+    local timezone=""
+    local localtime=""
+    local timezone_files_root=/usr/share/zoneinfo
+    local real_localtime=${timezone_files_root}/localtime
+
+    # This is only going to work if /etc/timezone exists
+    if [ ! -f /etc/timezone ] ; then
+        swi_log "/etc/timezone does not exist, not setting timezone"
+        return ${SWI_OK}
+    fi
+
+    # If /etc/localtime is not softlink, nothing we could do.
+    if [ ! -L /etc/localtime ] ; then
+        swi_log "/etc/localtime does not exist, not setting timezone"
+        return ${SWI_OK}
+    fi
+
+    # Also, /etc/localtime must point to proper timezone file.
+    localtime=$( readlink -f /etc/localtime )
+    if [ "x${localtime}" != "x${real_localtime}" ] ; then
+        # We are unable to perform this operation, but can continue.
+        swi_log "/etc/localtime is invalid, not setting timezone"
+        return ${SWI_OK}
+    fi
+
+    # See what the timezone is. This will be the name of the file
+    # in /usr/share/zoneinfo .
+    timezone=$( cat /etc/timezone )
+    swi_log "Using timezone ${timezone}..."
+
+    # Now, set proper timezone. If this operation fails, it is an error.
+    mount --bind ${timezone_files_root}/${timezone} ${real_localtime}
+    if [ $? -ne 0 ] ; then
+        swi_log "Moounting of ${timezone_files_root}/${timezone} failed."
+        ret=${SWI_ERR}
+    fi
+
+    return ${ret}
+}
+
+mount_early_unset_timezone()
+{
+    local real_localtime=${timezone_files_root}/localtime
+
+    # Do not care about the result.
+    umount -l ${real_localtime} &>/dev/null
+    return ${SWI_OK}
+}
+
 # Chooser.
 mount_early_start()
 {
@@ -1395,7 +1449,9 @@ mount_early_start()
         method_list_essential="
                                mount_early_pseudo
                                mount_early_other
-                               mount_early_create_dirs"
+                               mount_early_create_dirs
+                               mount_early_set_timezone
+                              "
     fi
 
     local method_list="
@@ -1426,6 +1482,7 @@ mount_early_stop()
                        mount_early_user_stop
                        mount_early_legato_stop
                        mount_early_userrw_stop
+                       mount_early_unset_timezone
                       "
 
     for method in ${method_list} ; do
