smack: Add exceptions for unlabelled internet access
SMACK netlabel and ipv6host exceptions are required to be declared, to
allow smack aware applications to be able to communicate with SMACK
unaware outside world.

Extend the fix from commit 3418e1a to handle cases of SMACK disabled
Legato on a SMACK enabled kernel.

While declaring the SMACK rules, declare the following exceptions too,
to allow unlabelled network packet flow.
echo 127.0.0.1 -CIPSO    > /sys/fs/smackfs/netlabel
echo 0.0.0.0/0 @         > /sys/fs/smackfs/netlabel
echo 0:0:0:0:0:0:0:0/0 @ > /sys/fs/smackfs/ipv6host

These rules could be made a bit more restrictive, allowing only a
specific label to access the network.

Resolves: LXSWIREF-1792
Change-Id: I2eb4ef72b08bdf08a713768f2fb1b76961079a15
Signed-off-by: Anju Kunjumon <akunjumon@sierrawireless.com>

diff --git a/meta-swi-virt/recipes-core/initscripts/files/smack b/meta-swi-virt/recipes-core/initscripts/files/smack
--- a/meta-swi-virt/recipes-core/initscripts/files/smack
+++ b/meta-swi-virt/recipes-core/initscripts/files/smack
@@ -4,6 +4,41 @@
 # import run environment
 source /etc/run.env
 
+# Add SMACK netlabel and ipv6host exceptions to grant applications
+# permission to communicate with the Internet via IPv4 and IPv6.
+# Reference: kernel.org smack admin-guide.
+add_system_smack_exceptions()
+{
+    local smack_net_label=/sys/fs/smackfs/netlabel
+    local smack_ipv6_host=/sys/fs/smackfs/ipv6host
+    # !TODO: Allow only a specific label. (Need change in Legato as well).
+    local single_label="@" # internet, access to all.
+    local host_ip="0.0.0.0/0" # all
+    local host_ip6="0:0:0:0:0:0:0:0/0" # all
+
+    # netlabel exceptions
+    local rule="127.0.0.1 -CIPSO"
+    echo "${rule}" > ${smack_net_label}
+    if [ $? -ne 0 ]; then
+        echo "${this_e}: Error loading system SMACK netlabel exception: ${rule}."
+        return ${SWI_ERR}
+    fi
+    rule="${host_ip} ${single_label}"
+    echo "${rule}" > ${smack_net_label}
+    if [ $? -ne 0 ]; then
+        echo "${this_e}: Error loading system SMACK netlabel exception: ${rule}."
+        return ${SWI_ERR}
+    fi
+
+    # IPv6 host exceptions
+    rule="${host_ip6} ${single_label}"
+    echo "${rule}" > ${smack_ipv6_host}
+    if [ $? -ne 0 ]; then
+        echo "${this_e}: Error loading system SMACK IPv6 host exception: ${rule}."
+        return ${SWI_ERR}
+    fi
+}
+
 # Add SMACK rules considered to be system related.
 # All the rules must be located in /etc/smack/accesses, because
 # we could also use smack userland tools to load the rules from
@@ -49,6 +84,11 @@ add_system_smack_rules()
 #
 case "$1" in
     start)
+        add_system_smack_exceptions
+        if [ $? -ne 0 ] ; then
+            echo "${this_e}: Failed to add system SMACK exceptions."
+            umount /sys/fs/smackfs >/dev/null 2>&1
+        fi
         add_system_smack_rules
         if [ $? -ne 0 ] ; then
             echo "${this_e}: Failed to add system SMACK rules."
